version: '3.7'

x-common-variables: &common-variables
  MYSQL_DATABASE: istl_db
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

networks:
      app-network:
        driver: bridge

services:
  mysql_db:
    image: mysql
    networks:
      - app-network
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./db:/docker-entrypoint-initdb.d/db"
    ports:
      - "5000:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost

  nginx:
    depends_on:
      - server
      - client
    restart: always
    networks:
      - app-network
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    networks:
      - app-network
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  client:
    stdin_open: true
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  adminer:
      image: adminer:latest
      networks:
      - app-network
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db